# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/Basys-3-Master.xdc

# IP: ip/clk_33_3_1/clk_33_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_33_3 || ORIG_REF_NAME==clk_33_3} -quiet] -quiet
