# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/Basys-3-Master.xdc

# IP: ip/double_mul/double_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==double_mul || ORIG_REF_NAME==double_mul} -quiet] -quiet

# IP: ip/double_div/double_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==double_div || ORIG_REF_NAME==double_div} -quiet] -quiet
