# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.srcs/sources_1/ip/clk_400/clk_400.xci
# IP: The module: 'clk_400' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.srcs/sources_1/ip/clk_400/clk_400.xci
# IP: The module: 'clk_400' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ADAM_LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/clk_400/clk_400_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_400'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
