# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/81524/OneDrive - The George Washington University/ADAM LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.srcs/sources_1/ip/double_add/double_add.xci
# IP: The module: 'double_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/81524/OneDrive - The George Washington University/ADAM LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/double_add/double_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_add'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/81524/OneDrive - The George Washington University/ADAM LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.srcs/sources_1/ip/double_add/double_add.xci
# IP: The module: 'double_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/81524/OneDrive - The George Washington University/ADAM LAB/IZ_Neuron_FPGA/FPGA_Implementation/DG_granule_model/DG_granule_model.gen/sources_1/ip/double_add/double_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_add'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
